// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5cEjHn2EXjlzDXdXs63xlYLysxBa0GAM',
    appId: '1:224919355663:web:48da06588e61060e273e7a',
    messagingSenderId: '224919355663',
    projectId: 'tiktok-clone-11b60',
    authDomain: 'tiktok-clone-11b60.firebaseapp.com',
    storageBucket: 'tiktok-clone-11b60.appspot.com',
    measurementId: 'G-148C1P427B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgqctTBieOW0Rj9T9oODyVyH3aMf3eZr0',
    appId: '1:224919355663:android:51fb5e6d812ccb89273e7a',
    messagingSenderId: '224919355663',
    projectId: 'tiktok-clone-11b60',
    storageBucket: 'tiktok-clone-11b60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx0EfsEYcTzf7YItzSjVfEqOjDWJsQ8To',
    appId: '1:224919355663:ios:35c2161e74fe3866273e7a',
    messagingSenderId: '224919355663',
    projectId: 'tiktok-clone-11b60',
    storageBucket: 'tiktok-clone-11b60.appspot.com',
    iosBundleId: 'com.example.nomadFlutterSecond',
  );
}
